services:
  db:
    image: postgres:15.3-alpine3.18
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - CORS_ORIGINS=${CORS_ORIGINS}
    ports:
      - "5432:5432"
    volumes:
      - ./pg-data:/var/lib/postgresql/data

  backend:
    build:
      context: app/
      dockerfile: ../docker/backend.Dockerfile
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DO_SPACES_ACCESS_KEY=${DO_SPACES_ACCESS_KEY}
      - DO_SPACES_SECRET_KEY=${DO_SPACES_SECRET_KEY}
      - DO_SPACES_ENDPOINT_URL=${DO_SPACES_ENDPOINT_URL}
      - DO_SPACES_BUCKET_NAME=${DO_SPACES_BUCKET_NAME}
      - TELEGRAM_NORTH_FPV_BOT_API_KEY=${TELEGRAM_NORTH_FPV_BOT_API_KEY}
      - TELEGRAM_NORTH_FPV_MAIN_CHANNEL=${TELEGRAM_NORTH_FPV_MAIN_CHANNEL}
      - FRONTEND_HOST=${FRONTEND_HOST}
      - ENV=dev
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./app:/app

  cron-worker:
    build:
      context: app/
      dockerfile: ../docker/cron.Dockerfile
    command: ["bash", "./cron-start.sh"]
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - TELEGRAM_BOT_API_KEY=${TELEGRAM_BOT_API_KEY}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FREE_CURRENCIES_API_URL=${FREE_CURRENCIES_API_URL}
      - FREE_CURRENCIES_API_KEY=${FREE_CURRENCIES_API_KEY}
      - ENV=dev
    volumes:
      - ./app:/app
    depends_on:
      - db

volumes:
  pg-data:
