version: "3.8"
services:
  db:
    image: postgres:15.3-alpine3.18
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./pg-data:/var/lib/postgresql/data

  backend:
    build:
      context: app/
      dockerfile: ../docker/backend.Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./app:/app

  worker:
    env_file:
      - .env
    build:
      context: app/
      dockerfile: ../docker/worker.Dockerfile
    restart: always
    volumes:
      - ./app:/app

volumes:
  pg-data:
