"""currency fix

Revision ID: 0189637337c1
Revises: ce041dcaa97e
Create Date: 2023-06-16 08:57:00.344933

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0189637337c1'
down_revision = 'ce041dcaa97e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'currency',
               existing_type=postgresql.ENUM('EUR', 'USD', 'AUD', 'CAD', 'GBP', name='currency'),
               nullable=True)
    op.alter_column('store', 'country_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('store', 'country_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('product', 'currency',
               existing_type=postgresql.ENUM('EUR', 'USD', 'AUD', 'CAD', 'GBP', name='currency'),
               nullable=False)
    # ### end Alembic commands ###
