"""product public id

Revision ID: 0361da449d4d
Revises: 3ff264bcda04
Create Date: 2023-05-29 10:59:05.308554

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "0361da449d4d"
down_revision = "3ff264bcda04"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("brand", "description_en")
    op.drop_column("continent", "name_en")
    op.drop_column("country", "name_en")
    op.add_column(
        "product",
        sa.Column(
            "public_id",
            sqlmodel.sql.sqltypes.GUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_product_public_id"), "product", ["public_id"], unique=False
    )
    op.create_index(op.f("ix_store_public_id"), "store", ["public_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_store_public_id"), table_name="store")
    op.drop_index(op.f("ix_product_public_id"), table_name="product")
    op.drop_column("product", "public_id")
    op.add_column(
        "country",
        sa.Column(
            "name_en", sa.VARCHAR(length=128), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "continent",
        sa.Column(
            "name_en", sa.VARCHAR(length=128), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "brand",
        sa.Column("description_en", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
