"""created_at clicked_product

Revision ID: 0c81eda79dbc
Revises: 0189637337c1
Create Date: 2023-08-12 13:49:33.055185

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0c81eda79dbc'
down_revision = '0189637337c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clicked_product', sa.Column('created_at', sa.DateTime(), server_default=sa.text('current_timestamp'), nullable=True))
    op.alter_column('product', 'currency',
               existing_type=postgresql.ENUM('EUR', 'USD', 'AUD', 'CAD', 'GBP', name='currency'),
               nullable=True)
    op.alter_column('store', 'country_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('store', 'country_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('product', 'currency',
               existing_type=postgresql.ENUM('EUR', 'USD', 'AUD', 'CAD', 'GBP', name='currency'),
               nullable=False)
    op.drop_column('clicked_product', 'created_at')
    # ### end Alembic commands ###
