"""last mod format

Revision ID: 12cdf23dc1a5
Revises: a13f9d473170
Create Date: 2023-10-08 15:15:28.166782

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "12cdf23dc1a5"
down_revision = "a13f9d473170"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "store_sitemap",
        sa.Column("lastmod_format", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.alter_column(
        "store_sitemap", "store_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "store_sitemap", "store_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_column("store_sitemap", "lastmod_format")
    # ### end Alembic commands ###
