"""Email verification

Revision ID: 1703e586cb6a
Revises: 7fc89f84f9a6
Create Date: 2023-11-12 12:13:22.851308

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "1703e586cb6a"
down_revision = "7fc89f84f9a6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_verification_code",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("current_timestamp"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("expiration_date", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "code"),
    )
    op.add_column(
        "user",
        sa.Column(
            "is_email_verified",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_email_verified")
    op.drop_table("email_verification_code")
    # ### end Alembic commands ###
