"""user phonenumber

Revision ID: 298f007f863e
Revises: 7e622d50c99d
Create Date: 2023-11-20 10:37:12.884093

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "298f007f863e"
down_revision = "7e622d50c99d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("phone_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "user_settings",
        sa.Column(
            "preferred_contact_method",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_settings", "preferred_contact_method")
    op.drop_column("user", "phone_number")
    # ### end Alembic commands ###
