"""wishlist

Revision ID: 2b629d663d75
Revises: 1703e586cb6a
Create Date: 2023-11-12 15:19:58.761781

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2b629d663d75"
down_revision = "1703e586cb6a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "favorite_product",
        sa.Column(
            "public_id",
            sqlmodel.sql.sqltypes.GUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("current_timestamp"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "product_id"),
    )
    op.create_index(
        op.f("ix_favorite_product_public_id"),
        "favorite_product",
        ["public_id"],
        unique=False,
    )
    op.alter_column(
        "product",
        "currency",
        existing_type=postgresql.ENUM(
            "EUR", "USD", "AUD", "CAD", "GBP", name="currency"
        ),
        nullable=False,
    )
    op.alter_column(
        "shipping_method",
        "currency",
        existing_type=postgresql.ENUM(
            "EUR", "USD", "AUD", "CAD", "GBP", name="currency"
        ),
        nullable=False,
    )
    op.alter_column(
        "store",
        "currency",
        existing_type=postgresql.ENUM(
            "EUR", "USD", "AUD", "CAD", "GBP", name="currency"
        ),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "store",
        "currency",
        existing_type=postgresql.ENUM(
            "EUR", "USD", "AUD", "CAD", "GBP", name="currency"
        ),
        nullable=True,
    )
    op.alter_column(
        "shipping_method",
        "currency",
        existing_type=postgresql.ENUM(
            "EUR", "USD", "AUD", "CAD", "GBP", name="currency"
        ),
        nullable=True,
    )
    op.alter_column(
        "product",
        "currency",
        existing_type=postgresql.ENUM(
            "EUR", "USD", "AUD", "CAD", "GBP", name="currency"
        ),
        nullable=True,
    )
    op.drop_index(op.f("ix_favorite_product_public_id"), table_name="favorite_product")
    op.drop_table("favorite_product")
    # ### end Alembic commands ###
