"""remove import query

Revision ID: 4b9d8ecb80c7
Revises: 12cdf23dc1a5
Create Date: 2023-10-09 09:01:34.718676

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4b9d8ecb80c7"
down_revision = "12cdf23dc1a5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("product_import_query_id_fkey", "product", type_="foreignkey")
    op.drop_column("product", "import_query_id")
    op.drop_table("import_query")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product",
        sa.Column("import_query_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "product_import_query_id_fkey",
        "product",
        "import_query",
        ["import_query_id"],
        ["id"],
    )
    op.create_table(
        "import_query",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("text", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("priority", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("products_clicks", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "priority_score",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("brand_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["brand_id"], ["brand.id"], name="import_query_brand_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="import_query_pkey"),
    )
    # ### end Alembic commands ###
