"""Prevent to categorize twice the same product

Revision ID: 61f65d8e36b8
Revises: 862f1b677891
Create Date: 2023-10-09 17:12:35.636848

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "61f65d8e36b8"
down_revision = "862f1b677891"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("product", sa.Column("categorized_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product", "categorized_at")
    # ### end Alembic commands ###
