"""sitemaps

Revision ID: 70981cc58670
Revises: 393a17639193
Create Date: 2023-10-07 09:16:33.253946

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "70981cc58670"
down_revision = "393a17639193"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "store_sitemap",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("current_timestamp"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["store.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "store",
        "search_url",
        existing_type=sa.VARCHAR(),
        comment="DEPRECATED! The base url of the search page, like website.com/search?q=",
        existing_comment="The base url of the search page, like website.com/search?q=",
        existing_nullable=False,
    )
    op.alter_column(
        "store",
        "search_tag",
        existing_type=sa.VARCHAR(),
        comment="DEPRECATED! The nearest HTML tag for each product item displayed in the result page",
        existing_comment="The nearest HTML tag for each product item displayed in the result page",
        existing_nullable=False,
    )
    op.alter_column(
        "store",
        "search_class",
        existing_type=sa.VARCHAR(),
        comment="DEPRECATED! The nearest CSS class for the search_tag",
        existing_comment="The nearest CSS class for the search_tag",
        existing_nullable=False,
    )
    op.alter_column(
        "store",
        "search_link",
        existing_type=sa.VARCHAR(),
        comment="DEPRECATED! The nearest CSS class from where to search the product page link",
        existing_comment="The nearest CSS class from where to search the product page link",
        existing_nullable=False,
    )
    op.alter_column(
        "store",
        "search_next_page",
        existing_type=sa.VARCHAR(),
        comment="DEPRECATED! The nearest CSS class from where to get the next page link",
        existing_comment="The nearest CSS class from where to get the next page link",
        existing_nullable=True,
    )
    op.alter_column(
        "store",
        "search_page_param",
        existing_type=sa.VARCHAR(),
        comment="DEPRECATED! The query param used in alternative to the next page link",
        existing_comment="The query param used in alternative to the next page link",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "store",
        "search_page_param",
        existing_type=sa.VARCHAR(),
        comment="The query param used in alternative to the next page link",
        existing_comment="DEPRECATED! The query param used in alternative to the next page link",
        existing_nullable=True,
    )
    op.alter_column(
        "store",
        "search_next_page",
        existing_type=sa.VARCHAR(),
        comment="The nearest CSS class from where to get the next page link",
        existing_comment="DEPRECATED! The nearest CSS class from where to get the next page link",
        existing_nullable=True,
    )
    op.alter_column(
        "store",
        "search_link",
        existing_type=sa.VARCHAR(),
        comment="The nearest CSS class from where to search the product page link",
        existing_comment="DEPRECATED! The nearest CSS class from where to search the product page link",
        existing_nullable=False,
    )
    op.alter_column(
        "store",
        "search_class",
        existing_type=sa.VARCHAR(),
        comment="The nearest CSS class for the search_tag",
        existing_comment="DEPRECATED! The nearest CSS class for the search_tag",
        existing_nullable=False,
    )
    op.alter_column(
        "store",
        "search_tag",
        existing_type=sa.VARCHAR(),
        comment="The nearest HTML tag for each product item displayed in the result page",
        existing_comment="DEPRECATED! The nearest HTML tag for each product item displayed in the result page",
        existing_nullable=False,
    )
    op.alter_column(
        "store",
        "search_url",
        existing_type=sa.VARCHAR(),
        comment="The base url of the search page, like website.com/search?q=",
        existing_comment="DEPRECATED! The base url of the search page, like website.com/search?q=",
        existing_nullable=False,
    )
    op.drop_table("store_sitemap")
    # ### end Alembic commands ###
