"""admin user

Revision ID: 77003b26de36
Revises: e9d2b7780c5f
Create Date: 2023-05-25 09:19:35.293402

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "77003b26de36"
down_revision = "e9d2b7780c5f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        INSERT INTO "user" (id, created_at, is_active, first_name, last_name, email, password, is_superuser) 
        VALUES (1, current_timestamp, TRUE, 'Luca', 'Admin', 'lucapalonca@gmail.com', '$2y$10$rkAUTInEpo1CSJVEze0MSeJC/0YyhHmNqs8IvUz4osIrqJMW5r14u', TRUE)
     """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DELETE "user" WHERE id = 1 AND is_superuser IS TRUE')
    # ### end Alembic commands ###
