"""store search deprecation

Revision ID: 7fc89f84f9a6
Revises: 2f66042ec8f3
Create Date: 2023-10-24 08:34:46.060729

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "7fc89f84f9a6"
down_revision = "2f66042ec8f3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "store",
        "search_url",
        existing_type=sa.VARCHAR(),
        nullable=True,
        existing_comment="DEPRECATED! The base url of the search page, like website.com/search?q=",
    )
    op.alter_column(
        "store",
        "search_tag",
        existing_type=sa.VARCHAR(),
        nullable=True,
        existing_comment="DEPRECATED! The nearest HTML tag for each product item displayed in the result page",
    )
    op.alter_column(
        "store",
        "search_class",
        existing_type=sa.VARCHAR(),
        nullable=True,
        existing_comment="DEPRECATED! The nearest CSS class for the search_tag",
    )
    op.alter_column(
        "store",
        "search_link",
        existing_type=sa.VARCHAR(),
        nullable=True,
        existing_comment="DEPRECATED! The nearest CSS class from where to search the product page link",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "store",
        "search_link",
        existing_type=sa.VARCHAR(),
        nullable=False,
        existing_comment="DEPRECATED! The nearest CSS class from where to search the product page link",
    )
    op.alter_column(
        "store",
        "search_class",
        existing_type=sa.VARCHAR(),
        nullable=False,
        existing_comment="DEPRECATED! The nearest CSS class for the search_tag",
    )
    op.alter_column(
        "store",
        "search_tag",
        existing_type=sa.VARCHAR(),
        nullable=False,
        existing_comment="DEPRECATED! The nearest HTML tag for each product item displayed in the result page",
    )
    op.alter_column(
        "store",
        "search_url",
        existing_type=sa.VARCHAR(),
        nullable=False,
        existing_comment="DEPRECATED! The base url of the search page, like website.com/search?q=",
    )
    # ### end Alembic commands ###
