"""product sub category

Revision ID: 862f1b677891
Revises: fe22276932f3
Create Date: 2023-10-09 10:32:47.930443

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "862f1b677891"
down_revision = "fe22276932f3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("product", sa.Column("sub_category_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "product_subcategory_fk", "product", "category", ["sub_category_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("product_subcategory_fk", "product", type_="foreignkey")
    op.drop_column("product", "sub_category_id")
    # ### end Alembic commands ###
