"""Users public_id

Revision ID: 99db70c7ff3d
Revises: 0c81eda79dbc
Create Date: 2023-10-02 08:16:37.210476

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "99db70c7ff3d"
down_revision = "0c81eda79dbc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "public_id",
            sqlmodel.sql.sqltypes.GUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
    )
    op.create_index(op.f("ix_user_public_id"), "user", ["public_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_public_id"), table_name="user")
    op.drop_column("user", "public_id")
    # ### end Alembic commands ###
