"""sitemap label

Revision ID: a13f9d473170
Revises: 70981cc58670
Create Date: 2023-10-08 14:54:34.283672

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "a13f9d473170"
down_revision = "70981cc58670"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "store_sitemap",
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("store_sitemap", "label")
    # ### end Alembic commands ###
