"""user optional names

Revision ID: b6ef8486e950
Revises: 3c2ed604865a
Create Date: 2023-10-06 13:39:54.746492

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b6ef8486e950'
down_revision = '3c2ed604865a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'first_name', existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column('user', 'last_name', existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'last_name', existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column('user', 'first_name', existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
