"""favorite last price

Revision ID: c4252f788219
Revises: 4f38d755bac2
Create Date: 2024-06-12 09:16:30.931798

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c4252f788219'
down_revision = '4f38d755bac2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite_product', sa.Column('last_notified_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorite_product', 'last_notified_price')
    # ### end Alembic commands ###
