"""track geo info on clicked product

Revision ID: da22ce9e9901
Revises: 0361da449d4d
Create Date: 2023-06-02 05:41:41.365158

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da22ce9e9901'
down_revision = '0361da449d4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clicked_product', sa.Column('client_continent', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.add_column('clicked_product', sa.Column('client_country', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True))
    op.add_column('clicked_product', sa.Column('client_city', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True))
    op.drop_column('shipping_method', 'name_en')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipping_method', sa.Column('name_en', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('clicked_product', 'client_city')
    op.drop_column('clicked_product', 'client_country')
    op.drop_column('clicked_product', 'client_continent')
    # ### end Alembic commands ###
