"""product category

Revision ID: fe22276932f3
Revises: 4b9d8ecb80c7
Create Date: 2023-10-09 10:17:31.130781

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "fe22276932f3"
down_revision = "4b9d8ecb80c7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("current_timestamp"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name_it", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["category.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("product", sa.Column("category_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "product_category_fk", "product", "category", ["category_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("product_category_fk", "product", type_="foreignkey")
    op.drop_column("product", "category_id")
    op.drop_table("category")
    # ### end Alembic commands ###
