"""traking used products views

Revision ID: ff80bcb1e2b8
Revises: 298f007f863e
Create Date: 2023-11-21 13:20:06.384477

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ff80bcb1e2b8"
down_revision = "298f007f863e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_email_wait_list",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("current_timestamp"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "used_product_view",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("current_timestamp"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["used_product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("used_product_view")
    op.drop_table("user_email_wait_list")
    # ### end Alembic commands ###
